[package]
name = "cipher-cli"
version = "0.1.0"
authors = ["Richard Sunderland <dev@sunderlandfamily.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.5"
rand = "0.7.3"
hex = "0.4.2"
aes-gcm = "0.3.2"